apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: cloud-deploy-mp1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: cluster-1
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cluster-1
description: development cluster
gke:
 cluster: projects/rosy-spring-399707/locations/us-west4-b/clusters/cluster-1
