steps:
#Building the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/rosy-spring-399707/nginx1:v1', '.' ]
#Pushing the image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/rosy-spring-399707/nginx1:v1"]
#Starting the cloud deploy release to deploy the manifest
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create initial-release-1 \
    --delivery-pipeline=cloud-deploy-mp1 \
    --region=us-west4 \
    --source=./ \
    --images=nginx1=gcr.io/rosy-spring-399707/nginx1:v1
